name: main

on:
  push:

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run action
        uses: jedrzejginter/gh-actions-test/my-github-action@main
